### ISSUE TITLE
FInalize scoring of pilot participants

### ISSUE THREAD

**Issue by RCODI** [ironhacks/ironhacks-scoring-tools#1]
1) Context: Scoring metrics in markdown
2) Best Solution Metrics: MAPE, MSPE, MAPPE
3) IMPROVEMENT SPIRIT METRICS: NoteBook Effort, BigQuery Effort, Code_Change_Effort
4) Rule Validation Scoring: 
Code_Clone Metrics (Jaccard Index) - among participants code
Code_Clone External

**Comment by charrismatic** [comment]
for code clone we use https://github.com/kucherenko/jscpd
